# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

prayers = Prayer.create([{title: 'Me (David S.)', content: 'For confidence and peace.', postedby: 'David S.'}, {title: 'My family', content: 'We are looking for a new house for my parents.', postedby: 'Tamara L.'}])
emails = Email.create([{name: 'Ausenbaugh, Joyce', address: 'joyce.ausenbaugh@yahoo.com'},{name: 'Brazil, Jane', address: 'janebrazil1@comcast.net'},{name: 'Carmack, Carolyn', address: 'carolyncarmack@bellsouth.net'},{name: 'Carter, Donna', address: 'dcrn09@gmail.com'},{name: 'Cook, Elaine', address: 'cookslanding@aol.com'},{name: 'Cothran, Judy', address: 'judy_cothran@yahoo.com'},{name: 'Davis, Beth', address: 'Bethdavis1224@gmail.com'},{name: 'Early, Beverly', address: 'beverlye59@gmail.com'},{name: 'Edwards, Lou', address: 'louedwards@comcast.net'},{name: 'Eggert, Sue', address: 'Susabelle40@gmail.com'},{name: 'Farrow, Barbara', address: 'befarrow@att.net'},{name: 'Ford, Mary', address: 'mjford9346@yahoo.com'},{name: 'Harris, Patty', address: 'paharris29@att.net'},{name: 'Harvey, Connie', address: 'harveyc@realtracs.com'},{name: 'Heckle, Patti', address: 'pattiheckle@yahoo.com'},{name: 'Higgins, Lyn', address: 'lynhiggie@gmail.com'},{name: 'Hurley, Judy', address: 'judhrly@gmail.com'},{name: 'Kain, Sue', address: 'sbkain@comcast.net'},{name: 'Kitty, Laura', address: 'Laura.jones007@comcast.net'},{name: 'Lecomte, Betty', address: 'bettylecomte@att.net'},{name: 'Lee, Frances', address: 'flee5003@hotmail.com'},{name: 'Long, Laurie', address: 'lalong62@att.net'},{name: 'McBroom, Sharon', address: 'sharonmcbroom@comcast.net'},{name: 'Miller, Julie', address: 'jkayemiller@yahoo.com'},{name: 'Moorad, Judy', address: 'jmoorad2@comcast.net'},{name: 'Neill, Cheryl', address: 'cmn210@earthlink.net'},{name: 'Newbill, Kay', address: 'kaynewbill@hotmail.com'},{name: 'Panarelli, Arleen', address: 'loupanarelli1@comcast.net'},{name: 'Phillippie, Bonita', address: 'bphillippie@yahoo.com'},{name: 'Phillips, Sandra', address: 'phillipss7@yahoo.com'},{name: 'Plummer, Sonja', address: 's-pplummer@juno.com'},{name: 'Poland, Deborah', address: 'deb@deborahpoland.com'},{name: 'Radestock, Carol', address: 'Cradestock@bakerdonelson.com'},{name: 'Reynolds, Janet', address: 'janet.rey01@att.net'},{name: 'Robertson, Deborah', address: 'leigh_bible7@yahoo.com'},{name: 'Scruggs, Florence', address: 'flrscrg@bellsouth.net'},{name: 'Semmes, Sherrie', address: 'sherrie7777@comcast.net'},{name: 'Simpson, Jane', address: 'janebelle@comcast.net'},{name: 'Walker, Jean', address: 'ewalker818@gmail.com'},{name: 'Webb, Mary', address: 'mnkwebb@aol.com'},{name: 'Webb, Nina', address: 'nowebb@comcast.net'},{name: 'Wiseman, Betty', address: 'betty.wiseman@belmont.edu'}])
